version: "3.9"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    volumes:
      - "/app/node_modules"
      - "./:/app"
