name: Release

on:
  push:
    branches: [master]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint

      - name: Format code
        run: yarn format

      - name: Build image
        run: yarn docker:start
